import { Injectable, NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import {
  And,
  Between,
  LessThan,
  LessThanOrEqual,
  MoreThanOrEqual,
  Repository,
} from "typeorm";
import { ReservationEntity } from "../reservation/entities/reservation.entity";
import { PaymentEntity } from "../payment/entities/payment.entity";
import { AnalysisDto } from "./dto/deposit.dto";
import { OrderStatus } from "../orders/utils/order.status.enum";
import { BranchEntity } from "../branch/entities/branch.entity";
import { EmployeeEntity } from "../employee/entities/employee.entity";
import { CustomerEntity } from "../customer/entities/customer.entity";
import { ServiceEntity } from "../service/entities/service.entity";
import { OfferEntity } from "../offer/entities/offer.entity";
import { SharableOfferEntity } from "../sharable-offer/entities/sharable-offer.entity";
import { OfferReportDto } from "./dto/get.offer.report.dto";
import { SharableOfferReportDto } from "./dto/get.sharable.offer.report.dto";
import { GetServiceReportDto } from "./dto/get.service.report.dto";
import { GetPaymentMethodReportDto } from "./dto/get.payment.report.dto";
import { OrderEntity } from "../orders/entities/order.entity";
import { GenerateOrderReportDto } from "./dto/get.orders.report.dto";
import { GetTotalDepositsDto } from "./dto/get.total.depost.branch.dto";
import { GetTotalRefundsDto } from "./dto/get.total.branch.refund.dto";
import { Postion } from "../postion/utils/postion.enum";
import { Role } from "../user/utils/user.enum";
import { PaymentStatus } from "../orders/utils/payment.status.enum";

@Injectable()
export class AnalysisService {
  constructor(
    @InjectRepository(ReservationEntity)
    private readonly ReservationRepository: Repository<ReservationEntity>,
    @InjectRepository(PaymentEntity)
    private readonly PaymentRepository: Repository<PaymentEntity>,

    @InjectRepository(BranchEntity)
    private readonly BranchRepository: Repository<BranchEntity>,

    @InjectRepository(EmployeeEntity)
    private readonly EmployeeRepository: Repository<EmployeeEntity>,

    @InjectRepository(CustomerEntity)
    private readonly CustomerRepository: Repository<CustomerEntity>,

    @InjectRepository(ServiceEntity)
    private readonly ServiceRepository: Repository<ServiceEntity>,

    @InjectRepository(OfferEntity)
    private readonly OfferRepository: Repository<OfferEntity>,

    @InjectRepository(SharableOfferEntity)
    private readonly SharableOfferRepository: Repository<SharableOfferEntity>,

    @InjectRepository(OrderEntity)
    private readonly OrderRepository: Repository<OrderEntity>,
  ) {}

  /* -------------------------------------------------------------------------- */
  /*                                   offers                                   */
  /* -------------------------------------------------------------------------- */
  async getOfferReport(filterDto: OfferReportDto): Promise<any> {
    const { fromDate, toDate, isActive, page, limit } = filterDto;

    const query = this.OfferRepository.createQueryBuilder("offer")
      .leftJoin("offer.services", "service")
      .select([
        "offer.id",
        "offer.offerName",
        "offer.startDateTime",
        "offer.endDateTime",
        "offer.discountPercentage",
        "offer.usageCount",
        "SUM(service.price * offer.usageCount) as totalRevenue", // Calculate total revenue
      ])
      .groupBy("offer.id");

    if (fromDate) {
      query.andWhere("offer.startDateTime >= :fromDate", { fromDate });
    }

    if (toDate) {
      query.andWhere("offer.endDateTime <= :toDate", { toDate });
    }

    if (isActive !== undefined) {
      query.andWhere("offer.isActive = :isActive", { isActive });
    }

    const result = await query
      .orderBy("offer.offerName", "ASC")
      .skip((page - 1) * limit)
      .take(limit)
      .getRawMany();

    return result;
  }

  // // Calculate total revenue generated by this offer
  // async calculateTotalRevenue(offerId: string): Promise<number> {
  //   const result = await this.ServiceRepository
  //     .createQueryBuilder('service') // Alias for ServiceEntity
  //     .leftJoin('service.offers', 'offer') // Joining with OfferEntity
  //     .select('SUM(service.price)', 'totalRevenue') // Calculating total revenue
  //     .where('offer.id = :offerId', { offerId }) // Filtering by offerId
  //     .getRawOne();

  //   return result?.totalRevenue || 0; // Returning total revenue or 0 if not found
  // }

  // // Calculate revenue per service for the offer
  // async getRevenuePerService(offerId: string): Promise<any[]> {
  //   const result = await this.ServiceRepository
  //     .createQueryBuilder('service')
  //     .leftJoin('service.offers', 'offer')
  //     .select(['service.name', 'SUM(service.price) AS revenue'])
  //     .where('offer.id = :offerId', { offerId })
  //     .groupBy('service.id')
  //     .getRawMany();

  //   return result;
  // }

  /* -------------------------------------------------------------------------- */
  /*                               Sharable Offers                              */
  /* -------------------------------------------------------------------------- */

  async getSharableOfferReport(
    filterDto: SharableOfferReportDto,
  ): Promise<any> {
    const { fromDate, toDate, isActive, page, limit } = filterDto;

    const query = this.SharableOfferRepository.createQueryBuilder(
      "sharableOffer",
    )
      .leftJoin("sharableOffer.services", "service")
      .select([
        "sharableOffer.id",
        "sharableOffer.offerName",
        "sharableOffer.startDateTime",
        "sharableOffer.endDateTime",
        "sharableOffer.discountPercentage",
        "sharableOffer.usageCount",
        "SUM(service.price * sharableOffer.usageCount) as totalRevenue", // Calculate total revenue
      ])
      .groupBy("sharableOffer.id");

    if (fromDate) {
      query.andWhere("sharableOffer.startDateTime >= :fromDate", { fromDate });
    }

    if (toDate) {
      query.andWhere("sharableOffer.endDateTime <= :toDate", { toDate });
    }

    if (isActive !== undefined) {
      query.andWhere("sharableOffer.isActive = :isActive", { isActive });
    }

    const result = await query
      .orderBy("sharableOffer.offerName", "ASC")
      .skip((page - 1) * limit)
      .take(limit)
      .getRawMany();

    return result;
  }

  /* -------------------------------------------------------------------------- */
  /*                                  services                                  */
  /* -------------------------------------------------------------------------- */
  async getServiceReport(query: GetServiceReportDto): Promise<any> {
    const { page, limit, fromDate, toDate } = query;

    const queryBuilder = this.ServiceRepository.createQueryBuilder("service")
      .leftJoin("service.reservations", "reservation")
      .leftJoin("reservation.customer", "customer")
      .select([
        "service.id AS service_id",
        "service.arabic_Name AS service_arabic_name",
        "service.english_Name AS service_english_name",
        "service.price AS service_price",
        "COALESCE(COUNT(DISTINCT reservation.id), 0) AS usagecount",
        "COALESCE(COUNT(DISTINCT customer.id), 0) AS customercount",
        "COALESCE(COUNT(DISTINCT reservation.id) * service.price, 0) AS totalrevenue",
      ]);

    // Apply date range filters if provided
    if (fromDate) {
      queryBuilder.where("reservation.date >= :fromDate", { fromDate });
    }
    if (toDate) {
      queryBuilder.andWhere("reservation.date <= :toDate", { toDate });
    }

    queryBuilder.groupBy("service.id");

    // Implement pagination
    const services = await queryBuilder
      .skip((page - 1) * limit)
      .take(limit)
      .getRawMany();

    // Calculate total revenue for all services
    const totalRevenueForAllServices = services.reduce(
      (sum, service) => sum + (parseFloat(service.totalrevenue) || 0),
      0,
    );

    // Return paginated services and total revenue
    return {
      services,
      totalRevenueForAllServices,
      page,
      limit,
    };
  }

  /* -------------------------------------------------------------------------- */
  /*                                   Payment                                  */
  /* -------------------------------------------------------------------------- */

  async getPaymentMethodReport(query: GetPaymentMethodReportDto): Promise<any> {
    const { fromDate, toDate, page, limit } = query;

    const queryBuilder = this.PaymentRepository.createQueryBuilder("payment")
      .leftJoin("payment.reservation", "reservation")
      .select([
        "payment.methodEnglish AS methodEnglish",
        "payment.methodArabic AS methodArabic",
        "COUNT(payment.id) AS usageCount", // Count how many times the payment method is used
        "SUM(reservation.totalPrice) AS totalRevenue", // Assuming `totalPrice` is the amount paid in the reservation
      ]);

    // Apply date range filters if provided
    if (fromDate) {
      queryBuilder.where("reservation.createdAt >= :fromDate", { fromDate });
    }
    if (toDate) {
      queryBuilder.andWhere("reservation.createdAt <= :toDate", { toDate });
    }

    // Group by all selected fields to avoid SQL errors
    queryBuilder.groupBy("payment.methodEnglish, payment.methodArabic");

    // Implement pagination
    const paymentMethods = await queryBuilder
      .skip((page - 1) * limit)
      .take(limit)
      .getRawMany();

    // Calculate total count of payment methods for pagination
    const [result, total] = await queryBuilder.getManyAndCount();

    return {
      paymentMethods,
      totalCount: total, // Total count of payment methods without pagination
      page,
      limit,
    };
  }

  /* -------------------------------------------------------------------------- */
  /*                                 Reservation                                */
  /* -------------------------------------------------------------------------- */

  // Get reservation report with optional date range
  async getReservationReport(
    fromDate?: Date,
    toDate?: Date,
    page?: number,
    limit?: number,
  ): Promise<any> {
    const query = this.ReservationRepository.createQueryBuilder(
      "reservation",
    ).leftJoinAndSelect("reservation.order", "order"); // Ensure the order is joined

    // Filter for createdAt dates
    if (fromDate) {
      query.andWhere("reservation.createdAt >= :fromDate", { fromDate });
    }

    if (toDate) {
      query.andWhere("reservation.createdAt <= :toDate", { toDate });
    }

    // Filter out canceled reservations
    query.andWhere("order.status != :canceledStatus", {
      canceledStatus: OrderStatus.Canceled,
    });

    // Total number of reservations
    const totalReservations = await query.getCount();

    // Total revenue from non-canceled reservations
    const totalRevenue = await query
      .select("SUM(reservation.totalPrice)", "totalRevenue")
      .getRawOne();

    // New customers
    const newCustomers = await query
      .select("COUNT(DISTINCT reservation.customerId)", "newCustomers") // Renamed to newCustomers
      .getRawOne();

    // Reservations by Branch with details
    const reservationsByBranch = await query
      .select(
        "branch.id as branchId, branch.name as branchName, branch.location as branchLocation, COUNT(reservation.id) as count",
      )
      .leftJoin("reservation.branch", "branch")
      .groupBy("branch.id, branch.name, branch.location")
      .getRawMany();

    // Reservations by Service with details
    const reservationsByService = await query
      .select(
        "service.id as serviceId, service.english_Name as serviceName, COUNT(reservation.id) as count",
      )
      .leftJoin("reservation.services", "service")
      .groupBy("service.id, service.english_Name") // Correcting to use the actual column name
      .getRawMany();

    // Apply pagination only if page and limit are provided
    let reservations = [];
    let totalCount = totalReservations;

    if (page && limit) {
      [reservations, totalCount] = await query
        .skip((page - 1) * limit) // Calculate offset
        .take(limit) // Set limit
        .getManyAndCount(); // Get results and count
    } else {
      // If no pagination parameters are provided, fetch all records
      reservations = await query.getMany();
    }

    return {
      totalReservations: totalCount,
      totalRevenue: totalRevenue?.totalRevenue || 0,
      newCustomers: newCustomers?.newCustomers || 0, // Updated here as well
      reservationsByBranch,
      reservationsByService,
      reservations, // Include paginated reservations
    };
  }

  /* -------------------------------------------------------------------------- */
  /*                                  Employees                                 */
  /* -------------------------------------------------------------------------- */

  // async getCoordinatorsAndReceptionistsReservations(fromDate: Date, toDate: Date) {
  //   // Define the positions to filter
  //   const positions = [Postion.COORDINATOR, Postion.RECEPTIONIST];
  //   console.log('Filtering positions:', positions);
  //   console.log('Date Range:', { fromDate, toDate });

  //   // Create the query builder for employees
  //   const employees = await this.EmployeeRepository.createQueryBuilder('employee')
  //     .leftJoinAndSelect('employee.branch', 'branch')
  //     .leftJoinAndSelect('employee.reservations', 'reservations')
  //     .leftJoinAndSelect('employee.orders', 'orders')
  //     .leftJoinAndSelect('orders.receipts', 'receipts')
  //     .leftJoinAndSelect('employee.position', 'position') // Correctly joining the position
  //     .where('position.postion IN (:...positions)', { positions }) // Use the alias 'position'
  //     .andWhere('(' +
  //       '(reservations.createdAt BETWEEN :fromDate AND :toDate) OR ' +
  //       '(reservations.createdAt IS NULL))', { fromDate, toDate })
  //     .andWhere('(' +
  //       '(orders.createdAt BETWEEN :fromDate AND :toDate) OR ' +
  //       '(orders.createdAt IS NULL))', { fromDate, toDate })
  //     .select([
  //       'employee.id AS employee_id',
  //       'employee.english_Name',
  //       'employee.arabic_Name',
  //       'position.postion AS position', // Changed to match the new alias
  //       'branch.id AS branch_id', // Added branch ID
  //       'branch.name AS branch_name', // Added branch name
  //       'branch.location AS branch_location', // Added branch location
  //       'COUNT(DISTINCT reservations.id) AS totalReservationsCreated', // Count unique reservations
  //       'COUNT(DISTINCT orders.id) AS totalOrdersCreated', // Count unique orders
  //       'SUM(receipts.totalPayment) AS totalRevenue',
  //     ])
  //     .groupBy('employee.id, branch.id, branch.name, branch.location, employee.english_Name, employee.arabic_Name, position.postion') // Use the new alias for grouping
  //     .getRawMany();

  //   console.log('Employees Query Result:', employees);

  //   // Generate the report date in YYYY-MM-DD format
  //   const reportDate = new Date().toISOString().split('T')[0];
  //   console.log('Report Date:', reportDate);

  //   // Return the report with employee details
  //   return {
  //     date: reportDate,
  //     totalEmployees: employees.length,
  //     details: employees.map(employee => ({
  //       id: employee.employee_id,
  //       names: {
  //         englishName: employee.english_Name,
  //         arabicName: employee.arabic_Name,
  //       },
  //       position: employee.position, // Changed to match the selected alias
  //       branch: {
  //         id: employee.branch_id, // Include branch ID
  //         name: employee.branch_name, // Include branch name
  //         location: employee.branch_location, // Include branch location
  //       },
  //       metrics: {
  //         totalReservationsCreated: employee.totalReservationsCreated,
  //         totalOrdersCreated: employee.totalOrdersCreated, // Ensure this is included
  //         totalRevenue: parseFloat(employee.totalRevenue) || 0,
  //       },
  //     })),
  //   };
  // }

  async getCoordinatorReceptionistOrderReport(
    fromDate?: Date,
    toDate?: Date,
    userId?: string,
    branchId?: string, // New parameter for branch ID
  ) {
    const roles = [
      Role.COORDINATOR,
      Role.RECEPTIONIST,
      Role.SUPERADMIN,
      Role.ADMIN,
    ];

    const query = this.OrderRepository.createQueryBuilder("o") // Alias for the order table
      .leftJoinAndSelect("o.createdBy", "user") // Join user who created the order
      .where("user.role IN (:...roles)", { roles }) // Filter users with specific roles
      .andWhere("o.status != :status", { status: OrderStatus.Canceled }) // Filter out canceled orders
      .select("user.id", "userId")
      .addSelect("user.username", "username")
      .addSelect("user.email", "email")
      .addSelect("user.role", "role") // Select the user role
      .addSelect("COUNT(o.id)", "orderCount") // Count the orders
      .addSelect("o.branch::json->>'name'", "branchName") // Extract the branch name from JSON
      .addSelect("o.branch::json->>'id'", "branchId") // Extract the branch ID from JSON
      .groupBy("user.id")
      .addGroupBy("user.username")
      .addGroupBy("user.email")
      .addGroupBy("user.role") // Group by the role
      .addGroupBy("o.branch::json->>'name'")
      .addGroupBy("o.branch::json->>'id'");

    // Add date filtering if fromDate or toDate are provided
    if (fromDate) {
      query.andWhere("o.createdAt >= :fromDate", { fromDate });
    }

    if (toDate) {
      query.andWhere("o.createdAt <= :toDate", { toDate });
    }

    // Add userId filtering if provided
    if (userId) {
      query.andWhere("user.id = :userId", { userId });
    }

    // Add branchId filtering if provided
    if (branchId) {
      query.andWhere("o.branch::json->>'id' = :branchId", { branchId });
    }

    const result = await query.getRawMany();

    return result;
  }

  async getPaymentMethodUsageReport(
    fromDate?: Date,
    toDate?: Date,
    branchId?: string,
  ) {
    const query = this.PaymentRepository.createQueryBuilder("p") // Alias for PaymentEntity
      .leftJoin("p.order", "o") // Join the related orders
      .leftJoin("o.reservation", "r") // Join the related reservation to access branch details
      .leftJoin("r.branch", "b") // Join the related branch details
      .where("o.status != :status", { status: OrderStatus.Canceled }) // Filter out canceled orders
      .select("p.methodEnglish", "methodEnglish") // Select payment method in English
      .addSelect("p.methodArabic", "methodArabic") // Select payment method in Arabic
      .addSelect("b.id", "branchId") // Select the branch ID
      .addSelect("b.name", "branchName") // Select the branch name
      .addSelect("COUNT(p.id)", "usageCount") // Count how many times the payment method was used
      .groupBy("b.id") // Group by branch ID
      .addGroupBy("b.name") // Group by branch name
      .addGroupBy("p.methodEnglish") // Group by payment method in English
      .addGroupBy("p.methodArabic"); // Group by payment method in Arabic

    // Apply date filters if provided
    if (fromDate) {
      query.andWhere("o.date >= :fromDate", { fromDate });
    }
    if (toDate) {
      query.andWhere("o.date <= :toDate", { toDate });
    }

    // Add branchId filtering if provided
    if (branchId) {
      query.andWhere("b.id = :branchId", { branchId });
    }

    const result = await query.getRawMany();

    // Format the result to organize by branch
    const formattedResult = result.reduce((acc, curr) => {
      const { branchId, branchName, methodEnglish, methodArabic, usageCount } =
        curr;

      // Check if the branch already exists in the accumulator
      let branch = acc.find((b) => b.branchId === branchId);
      if (!branch) {
        // If the branch doesn't exist, create a new entry
        branch = {
          branchId,
          branchName,
          paymentMethods: [], // Initialize an array for payment methods
        };
        acc.push(branch);
      }

      // Add the payment method details to the branch
      branch.paymentMethods.push({
        methodEnglish,
        methodArabic,
        usageCount: parseInt(usageCount, 10), // Convert usage count to a number
      });

      return acc;
    }, []);

    return formattedResult;
  }

  /* -------------------------------------------------------------------------- */
  /*                                   Orders                                   */
  /* -------------------------------------------------------------------------- */

  async generateOrderReport(
    dto: GenerateOrderReportDto,
    userId: string,
  ): Promise<any> {
    const { fromDate, toDate, page = 1, limit = 10 } = dto;

    // Get the requesting user's details
    const requestingUser = await this.EmployeeRepository.findOne({
      where: { id: userId },
      relations: ["branch", "position"],
    });

    // Prepare the query options
    const queryBuilder = this.OrderRepository.createQueryBuilder("order")
      .leftJoinAndSelect("order.reservation", "reservation")
      .skip((page - 1) * limit)
      .take(limit);

    // If user is a receptionist, filter by their branch ID
    if (
      requestingUser?.position?.postion === Postion.RECEPTIONIST &&
      requestingUser.branch
    ) {
      queryBuilder.andWhere("reservation.branchId = :branchId", {
        branchId: requestingUser.branch.id,
      });
    }

    // Apply date filtering if provided
    if (fromDate) {
      queryBuilder.andWhere("reservation.createdAt >= :fromDate", {
        fromDate: new Date(fromDate),
      });
    }

    if (toDate) {
      queryBuilder.andWhere("reservation.createdAt <= :toDate", {
        toDate: new Date(toDate),
      });
    }
    const branch = dto.branchId?.split(",") || [];
    if (branch.length > 0) {
      queryBuilder.andWhere("reservation.branchId IN (:...branch)", { branch });
    }

    // Fetch all orders with the applied filters and pagination
    const orders = await queryBuilder.getMany();

    // Initialize counts and total revenue
    const orderStatusCounts = {
      [OrderStatus.Canceled]: 0,
      [OrderStatus.Completed]: 0,
      [OrderStatus.Pending]: 0,
      [OrderStatus.InQueue]: 0,
      [OrderStatus.Working]: 0,
      [OrderStatus.Abscent]: 0,

      // Add other statuses as needed
    };

    let totalRevenue = 0;

    // Process orders to calculate refunds, revenue, and status counts
    const orderReports = orders.map((order) => {
      let refundAmount = 0; // Default refund amount
      let revenue = parseFloat(
        order.reservation?.totalPrice?.toString() || "0",
      ); // Ensure it's a number

      // Check if the order is canceled
      if (order.status === OrderStatus.Canceled) {
        // Determine refund amount based on payment status
        if (order.paymentStatus === PaymentStatus.Paid) {
          refundAmount = revenue; // Full refund if fully paid
        } else if (order.paymentStatus === PaymentStatus.PartiallyPaid) {
          refundAmount = parseFloat(
            order.reservation?.deposit?.toString() || "0",
          ); // Refund deposit if partially paid
        }
        revenue = 0; // Set revenue to 0 for canceled orders
      } else {
        // If not canceled, add to revenue
        totalRevenue += revenue; // Update total revenue
      }

      // Count order status
      orderStatusCounts[order.status] =
        (orderStatusCounts[order.status] || 0) + 1;

      return {
        orderId: order.id,
        refundAmount,
        revenue,
        paymentStatus: order.paymentStatus,
        status: order.status,
      };
    });

    return {
      orderReports,
      totalRevenue: totalRevenue.toFixed(2), // Format to 2 decimal places
      orderStatusCounts,
    };
  }

  async getTotalDepositsByBranch(dto: GetTotalDepositsDto): Promise<any> {
    const { branchId, fromDate, toDate } = dto;

    // Build the base query
    const query = this.ReservationRepository.createQueryBuilder("reservation")
      .select("reservation.branchId", "branchId")
      .addSelect("branch.name", "branchName") // Include branch name
      .addSelect("branch.location", "location") // Include branch location
      .addSelect("SUM(reservation.deposit)", "totalDeposits")
      .addSelect("SUM(reservation.totalPrice)", "totalPrice") // Include total price of reservations
      .leftJoin("reservation.branch", "branch") // Join with BranchEntity
      .groupBy("reservation.branchId")
      .addGroupBy("branch.name") // Group by branch name
      .addGroupBy("branch.location"); // Group by branch location

    // Apply filters if branchId is provided
    if (branchId) {
      query.andWhere("reservation.branchId = :branchId", { branchId });
    }

    // Apply date filtering if provided
    if (fromDate) {
      query.andWhere("reservation.createdAt >= :fromDate", {
        fromDate: new Date(fromDate),
      });
    }

    if (toDate) {
      query.andWhere("reservation.createdAt <= :toDate", {
        toDate: new Date(toDate),
      });
    }

    // Execute the query
    const deposits = await query.getRawMany();

    // Map the result to a more structured format, calculating totalRemaining
    return deposits.map((deposit) => ({
      branchId: deposit.branchId,
      branchName: deposit.branchName,
      location: deposit.location,
      totalDeposits: parseFloat(deposit.totalDeposits) || 0, // Ensure it's a number
      totalRemaining:
        parseFloat(deposit.totalPrice) -
        (parseFloat(deposit.totalDeposits) || 0), // Calculate remaining amount
    }));
  }

  async getAllPrices() {
    const result = await this.PaymentRepository.createQueryBuilder("payment")
      .select("SUM(payment.price)", "totalPrice")
      .getRawOne();

    return parseFloat(result.totalPrice || "0");
  }

  async getPricesGroupedByMethod() {
    const results = await this.PaymentRepository.createQueryBuilder("payment")
      .select("payment.methodEnglish", "method")
      .addSelect("SUM(payment.price)", "totalPrice")
      .groupBy("payment.methodEnglish")
      .getRawMany();

    return results.reduce((acc, result) => {
      acc[result.method] = parseFloat(result.totalPrice) || 0;
      return acc;
    }, {});
  }
  async getTotalReturnedMoneyFromCanceledOrdersByTimeRange(
    fromDate: Date,
    toDate: Date,
  ) {
    if (!fromDate || !toDate) {
      fromDate = new Date();
      toDate = new Date(Date.now() - 24 * 3600 * 1000 * 7);
    }
    const reservationsWithinTimeRange =
      await this.ReservationRepository.createQueryBuilder("reservation")
        .leftJoinAndSelect("reservation.order", "order")
        .where("order.status = :status", { status: OrderStatus.Canceled })
        .andWhere("reservation.start_Time BETWEEN :fromDate AND :toDate", {
          fromDate: fromDate,
          toDate: toDate,
        })
        .select([
          "reservation.id",
          "reservation.totalPrice",
          "reservation.deposit",
          "order.invoiceNumber",
        ])
        .getMany();

    const totalReturnedMoney = reservationsWithinTimeRange.reduce(
      (total, reservation) =>
        total +
        Number(reservation.deposit ?? 0) +
        Number(reservation.totalPrice ?? 0),
      0,
    );

    return totalReturnedMoney;
  }

  /* -------------------------------------------------------------------------- */
  /*                               Analysis Count                               */
  /* -------------------------------------------------------------------------- */
  async getCount(): Promise<{
    branchCount: number;
    employeeCount: number;
    customerCount: number;
    serviceCount: number;
    activeOffersCount: number;
    activeSharableOffersCount: number;
  }> {
    const branchCount = await this.BranchRepository.count();
    const employeeCount = await this.EmployeeRepository.count();
    const customerCount = await this.CustomerRepository.count();
    const serviceCount = await this.ServiceRepository.count();

    // Count active offers
    const activeOffersCount = await this.OfferRepository.count({
      where: { isActive: true }, // Assuming 'isActive' is the field to check for active offers
    });

    // Count active sharable offers
    const activeSharableOffersCount = await this.SharableOfferRepository.count({
      where: { isActive: true }, // Assuming 'isSharable' indicates sharable offers
    });

    return {
      branchCount,
      employeeCount,
      customerCount,
      serviceCount,
      activeOffersCount,
      activeSharableOffersCount,
    };
  }

  async getTotalRefunds(
    dto: GetTotalRefundsDto,
  ): Promise<
    {
      branchId: string;
      branchName: string;
      location: string;
      totalRefund: number;
    }[]
  > {
    const { branchId, fromDate, toDate } = dto;

    // Log the incoming DTO for debugging
    console.log("DTO:", dto);

    // Prepare the base query
    const query = this.OrderRepository.createQueryBuilder("order")
      .leftJoinAndSelect("order.reservation", "reservation") // Join with reservation
      .leftJoinAndSelect("reservation.branch", "branch"); // Join with branch

    // Apply date filtering if provided
    if (fromDate) {
      query.andWhere("order.createdAt >= :fromDate", {
        fromDate: new Date(fromDate),
      });
    }
    if (toDate) {
      query.andWhere("order.createdAt <= :toDate", {
        toDate: new Date(toDate),
      });
    }

    // If a branchId is provided, filter by branch id via reservation
    if (branchId) {
      query.andWhere("reservation.branch.id = :branchId", { branchId });
    }

    // Log the query before executing
    console.log("Query:", query.getSql(), query.getParameters());

    // Fetch all orders with the applied filters
    const orders = await query.getMany();

    // Log the fetched orders
    console.log("Fetched Orders:", orders);

    // Initialize refund amounts
    const branchRefunds: {
      [key: string]: { total: number; branchName: string; location: string };
    } = {};

    // Process orders to calculate refund amounts
    orders.forEach((order) => {
      if (!order.reservation || !order.reservation.branch) {
        return; // Skip orders without a reservation or branch
      }

      let refundAmount = 0; // Default refund amount
      const revenue = parseFloat(
        order.reservation.totalPrice?.toString() || "0",
      ); // Ensure it's a number

      // Check if the order is canceled
      if (order.status === OrderStatus.Canceled) {
        // Determine refund amount based on payment status
        if (order.paymentStatus === PaymentStatus.Paid) {
          refundAmount = revenue; // Full refund if fully paid
        } else if (order.paymentStatus === PaymentStatus.PartiallyPaid) {
          refundAmount = parseFloat(
            order.reservation.deposit?.toString() || "0",
          ); // Refund deposit if partially paid
        }
      }

      // Aggregate refund amount by branch using reservation's branchId
      const orderBranchId = order.reservation.branch.id; // Get branchId from reservation
      const branchName = order.reservation.branch.name; // Get branch name
      const location = order.reservation.branch.location; // Get branch location

      if (orderBranchId) {
        if (!branchRefunds[orderBranchId]) {
          branchRefunds[orderBranchId] = { total: 0, branchName, location }; // Initialize if not already set
        }
        branchRefunds[orderBranchId].total += refundAmount; // Add to total refund for that branch
      }
    });

    // Convert the refund amounts to an array of objects
    const result = Object.entries(branchRefunds).map(
      ([branchId, { total, branchName, location }]) => ({
        branchId,
        branchName,
        location,
        totalRefund: parseFloat(total.toFixed(2)), // Format to 2 decimal places
      }),
    );

    // Log the result before returning
    console.log("Total Refunds Result:", result);

    return result;
  }
}
