export enum Postion{
   
    BRANCHMANAGER = 'BRANCHMANAGER',
    COORDINATOR = 'COORDINATOR',
    RECEPTIONIST = 'RECEPTIONIST',
    ACCOUNTANT = 'ACCOUNTANT',
    ARTIST = 'ARTIST',
    ARTISTMANAGER ='ARTISTMANAGER',
    TABLEMANAGER = 'TABLEMANAGER'


}